/** Route segment labels for breadcrumbs (Thai UI). */
export const BREADCRUMB_MAP: Record<string, string> = {
  '/requests': 'สถานะ',
  '/cst': 'Compressive Strength Test',
  '/requests/new': 'จองคอนกรีต',
  '/profile': 'โปรไฟล์',
  '/preview': 'ตัวอย่าง',
  '/preview/forms': 'แบบฟอร์ม',
  '/admin': 'Dashboard',
  '/admin/users': 'Users Settings',
  '/admin/client': 'Client',
  '/admin/location': 'Location',
  '/admin/concrete-works': 'Concrete Works',
  '/admin/structure': 'Structure',
  '/admin/mixcode': 'Mixed Code',
  '/admin/abc-code': 'ABC Code',
  '/admin/wbs-code': 'WBS Code',
  '/admin/jobs': 'Jobs',
  '/admin/cst-machine': 'CST Machine',
}
